### ISSUE TITLE
Limit number of threads?

### ISSUE THREAD

**Issue by sjaenick** [f-kretschmer/bertax#1]
`bertax` seems to use 10 threads by default, how can this be changed?

Also, are there any experiences classifying
- short reads (up to 300bp)
- long error-prone reads (PacBio, Nanopore)?

**Comment by f-kretschmer** [comment]
Thanks for letting us now, an option to change the number of threads used is now available with `-t`/`--nr_threads`.

For now, there are no real experiences for these examples yet; while it is of course possible to classify shorter sequences, the accuracy will likely be lower.

**Comment by telatin** [comment]
I tried with 3 nanopore reads from S. aureus (500, 1600, 1850 bp respectively), with identity of 95% 95% 91% respectively. This was the output:
```
id                                                     superkingdom     phylum                genus                      
e2e2d7da-4009-4188-8358-f1203f08b135 runid=63ec8a9...  Bacteria (82%)   Firmicutes (69%)      Ooceraea (64%)             
558d99de-3abf-44af-bb40-3d84d44072e6 runid=63ec8a9...  Bacteria (91%)   Proteobacteria (27%)  Candidatus Kuenenia (18%)  
69eb249f-0228-4a05-80da-b4486b2105d1 runid=63ec8a9...  Eukaryota (52%)  Mollusca (36%)        Crassostrea (28%)          
```
Probably too noisy for Bertax

**Comment by flomock** [comment]
> 
> 
> `bertax` seems to use 10 threads by default, how can this be changed?
> 
> Also, are there any experiences classifying
> 
>     * short reads (up to 300bp)
> 
>     * long error-prone reads (PacBio, Nanopore)?

as both requests are addressed I now close the issue. Feel free to open a new one if further issues occur.
@telatin I think noise is certainly an issue, plus the genus Staphylococcus was not very common in the training set, so the results might be better for other more common genera.
