### ISSUE TITLE
How to train the "unknown" label during the training? 

### ISSUE THREAD

**Issue by zoubohao** [f-kretschmer/bertax#12]
Hello, Bertax team.

How should the unknown label be trained at each taxonomic rank, I wonder. In another meaning, it refers to the question of how to identify a sequence as "unknown" during training processing.

Could you provide me with some references or cites?

Thanks a lot if you can assist.

**Comment by flomock** [comment]
tldr.: use all training sequences you have, which do **not** belong to a class in the taxonomic rank you want to predict and label them as unknown.
Example:
Lets say you have sequences of 40 different species but for 10 of them you have very few sequences. You expect that the quality of prediction of the 10 species would in insufficient, therefore you do not want to train them as 10 different classes. Rather label all sequences belonging to these 10 Species as unknown. As a result you would train 31 classes in your model. 30 individual species and 1 unknown.

**Comment by flomock** [comment]
In our case we state in the description of table 2.: "However, all clades with less than 10,000 fragments were combined into a new class, “unknown,” for each taxonomic rank."

**Comment by zoubohao** [comment]
Thank you very much
