### ISSUE TITLE
Want to know the relationship between avep and confusion matrix

### ISSUE THREAD

**Issue by XLOXL** [f-kretschmer/bertax#15]
Hello, I would like to ask what is the meaning of the confusion matrix. As shown in the figure below, does 97% of Archaea refer to the proportion of the total Archaea sequence? How to calculate avep based on confusion matrix.
![image](https://github.com/f-kretschmer/bertax/assets/81890558/22f58781-792b-489a-af3f-f0b1a0351f52)

Please also ask where can I find the exact rate and recall rate of each sorting tool, because it is difficult to understand avep

**Comment by f-kretschmer** [comment]
Hi,

exact precision and recall values for each tool are in the PR plots in the Supplement of the PNAS BERTax publication (https://doi.org/10.1073/pnas.2122636119). Average Precision (we used [scikit learn to calculate it](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.average_precision_score.html)) behaves different based on which weighing that is applied, in the publication we report both "micro"- and "macro"-averaged values. In the confusion matrices, only the proportions are stated, so in this case 97% of the "real" Archaea sequences are predicted by DeepMicrobes to be Archaea.
