### ISSUE TITLE
suggestion: input check

### ISSUE THREAD

**Issue by telatin** [f-kretschmer/bertax#2]
When feeding by mistake a FASTQ file instead of a FASTA file the was no specific error/warning pointing to the problem. 
It could be useful to add some checks.

**Comment by flomock** [comment]
Good suggestion, I'll look into it and let you know when this feature is available.

**Comment by flomock** [comment]
It's now available :) 
From now only "proper" fasta files comprising of a header per sequence and a sequence comprising of characters usable in DNA sequences [http://insilico.ehu.es/restriction/Nucleotide_ambiguity_code.html](url) are allowed to be used.
