### ISSUE TITLE
Sharing the sequences used for pre-train

### ISSUE THREAD

**Issue by imasianxd** [f-kretschmer/bertax#3]
Hi, is it possible to share the sequences you used for pre-training in FASTA format?

**Comment by flomock** [comment]
Thanks for this request, 
you can find the pre-traininig data at:  DOI 10.17605/OSF.IO/QG6MV or [https://osf.io/qg6mv/](url) 
We will also add the other datasets within the next hours. And link the osf in the readme of this repository.

**Comment by imasianxd** [comment]
thank you.
