### ISSUE TITLE
IndexError appeared when using the "--output_ranks" parameter

### ISSUE THREAD

**Issue by EGTortuero** [f-kretschmer/bertax#7]
Hi,

I wanted to apply Bertax to classify several phages I had, and every time I run this program, it brings me the following error:

```
Traceback (most recent call last):
  File "/home/egtortuero/anaconda3/envs/bertax/bin/bertax", line 10, in <module>
    sys.exit(main())
  File "/home/egtortuero/anaconda3/envs/bertax/lib/python3.7/site-packages/bertax/bertax.py", line 113, in main
    for i in range(len(out_values[0]))]
  File "/home/egtortuero/anaconda3/envs/bertax/lib/python3.7/site-packages/bertax/bertax.py", line 113, in <listcomp>
    for i in range(len(out_values[0]))]
  File "/home/egtortuero/anaconda3/envs/bertax/lib/python3.7/site-packages/bertax/bertax.py", line 112, in <genexpr>
    max_field_lens = [max(o[i] for o in [list(map(len, o)) for o in out_values])
IndexError: list index out of range
```

I was using the Conda version of Bertax, and I ran it with the following command: 

`bertax Phage_A.fasta --output_ranks superkingdom kingdom phylum class family genus
`

Note that, when I tried to run it using the option before the FASTA file (as indicated in the help), the error was the following:

```
bertax --output_ranks superkingdom,kingdom,phylum,class,family,genus Phage_A.fasta
usage: bertax [-h] [-v] [-o FILE] [--conf_matrix_file FILE]
              [--sequence_split {equal_chunks,window}] [--chunk_predictions]
              [--running_window] [--running_window_stride STRIDE] [-s SIZE]
              [-C NR] [--output_ranks RANK [RANK ...]] [--no_confidence]
              [--batch_size BATCH_SIZE]
              fasta
bertax: error: the following arguments are required: fasta
```

Does it seem to only works to retrieve the "superkingdom phylum genus" output? What might happen if I want only to know to which (e.g.) phylum the sequence belongs?

If you need more information from my side, please feel free to reply to me.

Sorry for all inconvenience, and thank you in advance.

Best,

Enrique

**Comment by f-kretschmer** [comment]
Hi Enrique,

Thanks for the info, that is a bug right now and I already see the problem: Bertax has three predictions layers for superkingdom, phylum and genus (other ranks cannot be predicted). With `--output_ranks` the aim is to specify which of the rank-classifications will be displayed. I tested your input arguments and it seems right now the option only affects how many of the three mentioned ranks will be shown. The example in the README `bertax sequences.fa --output_ranks superkingdom` works but not if you only want one of the lower/more specific ranks like phylum. It should be an easy fix though, I'll keep you posted. Right now, a temporary workaround would be to output the results to a file (`bertax Phage_A.fasta -o bertax_out.tsv`) and then filter the output as to only show the desired columns with `cut` (`cut -d$'\t' -f1,4,5 bertax_out.tsv` to only show phylum output). Thanks again for finding this bug!

Best,
Fleming

**Comment by f-kretschmer** [comment]
It should now be fixed in all current versions (github, conda, docker) of bertax.
