### ISSUE TITLE
classification for genomes?

### ISSUE THREAD

**Issue by jianshu93** [f-kretschmer/bertax#8]
Dear bertax team,

I am wondering whether the query sequences could be genomes against database genomes and then found the best/significant hits to classify. In theory, this is the same with when query is sequences (short) right?

Thanks,

Jianshu

**Comment by flomock** [comment]
Hey @jianshu93, I think I do not fully understand your question. So, as I understand it, you want to first use a classic approach of finding the most similar sequence to your query in a database. In the next step you want to use this found sequence to classify via bertax. Correct? If not, please elaborate your question. 
And your question is if we would expect the found sequence to be of the same class as your query? Depending on the significance of the similarities between your query and the sequence in the database you are correct. However, if the query sequence is very short or the hit is far from perfect (therefor resulting in a low significance), this cannot be guaranteed. Furthermore, if you already know the taxonomic origin of the sequence in the database, using bertax may not be needed after all.

**Comment by jianshu93** [comment]
Thanks, so bertax is useful only when no similar hits in database was found, e.g., no idea what the query sequence belongs to (phylum for example), by identity based search.

Jianshu

**Comment by flomock** [comment]
I would say bertax is **most** usefule when no similar hits in database was found. However, if you have any reason to doubt the results of the identity based search (for example you get hits for lions but the sequenced sample was ocean water), bertax is useful to get an second opinion.
