### ISSUE TITLE
How to use with paired-end reads

### ISSUE THREAD

**Issue by vjoliveira** [f-kretschmer/bertax#9]
Hello,
 I have metagenomic paired-reads and would like to try the program. How do I use it?
my inputs: reads.R1.fq.gz and reads.R2.fq.gz

**Comment by f-kretschmer** [comment]
Hi, sorry for the delay. BERTax does not have a special mode for paired-end reads, it supports input by FASTA/multi-FASTA files, which you would have to build from your paired-end reads files by other measures.
